name: CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: |
          npm install
          npm run-script build
        env:
          REACT_APP_RapidAPI: '${{ secrets.REACT_APP_RAPID_API }}'
          REACT_APP_OMDB_Key: '${{ secrets.REACT_APP_OMDB_Key }}'
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages
          folder: build
